### ISSUE TITLE
Sanitization issues when saving CSS in the Legacy editor

### ISSUE THREAD

**Issue by jeherve** [georgestephanis/legacy-jetpack-custom-css-editor#4]
It seems that `'` and `>` symbols get escaped and changed into `&gt;` when saving CSS in the Legacy editor.

One can reproduce with the following CSS:

```css
#site-content > .container {
	background: url('/test1/wp-content/uploads/sites/1/2017/3/header-band.jpg') no-repeat transparent center top;
}
```

Reported here:
https://wordpress.org/support/topic/single-quotes-and-greater-than-escaping-issues/
